### ISSUE TITLE
Network error is not reported in errors and loading stays true

### ISSUE THREAD

**Issue by shlomokraus** [trojanowski/react-apollo-hooks#29] opened 2018-12-04 14:47 UTC
When useing `useQuery` (with suspense false), I get a network error, but the hook state stays with "loading: true" and errors undefined. networkState is still 1.

**Comment by umidbekkarimov** [comment] 2018-12-20 07:42
You can use `errorPolicy=all` as a workaround.
I guess the problem is that subscription error handler not passed here  https://github.com/trojanowski/react-apollo-hooks/blob/master/src/index.js#L31

**Comment by mateusznowosielski** [comment] 2018-12-23 00:38
I have exactly the same issue as @shlomokraus described. Changing `errorPolicy='all'` doesn't make any difference - I tried to set that for individual query and globally in ApolloClient level. With `<Suspense>` it works as expected. I'm using version 0.2.1.

**Comment by mateusznowosielski** [comment] 2018-12-24 21:44
Thanks @umidbekkarimov this is very helpful. Error gets properly handled, I also checked the `skip` option and I like the new typescript aspect. Hope it gets merged.

**Comment by trojanowski** [comment] 2018-12-27 18:05
I think it will be merged soon - I'm going to review it tomorrow.

**Closed** 2018-12-31 08:07 UTC

**Comment by cescox** [comment] 2019-09-12 08:04
Hello, any news on this issue?
