### ISSUE TITLE
How to get loading, error, data in useMutation

### ISSUE THREAD

**Issue by gijo-varghese** [trojanowski/react-apollo-hooks#116] opened 2019-03-23 09:12 UTC
From the docs, I couldn't find a way to to get `loading`, `error`, `data` for mutation. In `react-apollo` I could use  something like

```jsx
<Mutation mutation={RESEND_EMAIL}>
        {(resendEmail, { data }) => (
          <>
            {data && <Alert message="A new verification email has been sent" />}
            <Button onClick={resendEmail} size="large" type="primary">
              Resend verification email
            </Button>
          </>
        )}
      </Mutation>
```

Also, note that the success confirmation is shown from the jsx. Is it possible with `react-apollo-hooks`

**Comment by lukasluecke** [comment] 2019-03-23 16:48
See #93

**Comment by trojanowski** [comment] 2019-03-25 13:45
Yes, WIP PR is in #93. A snippet which provides this feature for the current version: <https://github.com/trojanowski/react-apollo-hooks/issues/20#issuecomment-459120477>. I'm closing this issue because it sounds like a duplicate of #20.

**Closed by trojanowski** 2019-03-25 13:45 UTC

**Comment by gijo-varghese** [comment] 2019-03-25 13:46
Any estimate on when this pr will be merged?
